--
-- PostgreSQL database dump
--

\restrict etgmknI7bMlJYB9rkT2ylQt81aqJtMrhZ6bPJPXGdJAu2LTOIvqg1xoQbxNjAVO

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asignacion_docente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asignacion_docente (
    id_asignacion_docente integer NOT NULL,
    empleado_id integer NOT NULL,
    materia_id integer NOT NULL,
    seccion_id integer NOT NULL,
    fecha_asignacion character varying(30) NOT NULL
);


ALTER TABLE public.asignacion_docente OWNER TO postgres;

--
-- Name: asignacion_docente_id_asignacion_docente_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.asignacion_docente_id_asignacion_docente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.asignacion_docente_id_asignacion_docente_seq OWNER TO postgres;

--
-- Name: asignacion_docente_id_asignacion_docente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.asignacion_docente_id_asignacion_docente_seq OWNED BY public.asignacion_docente.id_asignacion_docente;


--
-- Name: asignacion_docente_id_asignacion_docente_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asignacion_docente ALTER COLUMN id_asignacion_docente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asignacion_docente_id_asignacion_docente_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: asistencias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asistencias (
    idasis integer NOT NULL,
    asisestu character varying(30) NOT NULL,
    fecha date NOT NULL,
    verificar boolean NOT NULL
);


ALTER TABLE public.asistencias OWNER TO postgres;

--
-- Name: asistencias_idasis_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.asistencias_idasis_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.asistencias_idasis_seq OWNER TO postgres;

--
-- Name: asistencias_idasis_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.asistencias_idasis_seq OWNED BY public.asistencias.idasis;


--
-- Name: asistencias_idasis_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asistencias ALTER COLUMN idasis ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asistencias_idasis_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria (
    idseria integer NOT NULL,
    usuario_escritor_id character varying(20) NOT NULL,
    usuario_objeto_id character varying(20) NOT NULL,
    accion character varying(100) NOT NULL,
    datos_anteriores character varying(200),
    datos_nuevos character varying(200),
    fecha date NOT NULL
);


ALTER TABLE public.auditoria OWNER TO postgres;

--
-- Name: auditoria_idseria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.auditoria_idseria_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.auditoria_idseria_seq OWNER TO postgres;

--
-- Name: auditoria_idseria_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.auditoria_idseria_seq OWNED BY public.auditoria.idseria;


--
-- Name: auditoria_idseria_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auditoria ALTER COLUMN idseria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_idseria_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bloque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bloque (
    idbloque integer NOT NULL,
    horainicio character varying(100) NOT NULL,
    horafin character varying(100) NOT NULL
);


ALTER TABLE public.bloque OWNER TO postgres;

--
-- Name: bloque_idbloque_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bloque_idbloque_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bloque_idbloque_seq OWNER TO postgres;

--
-- Name: bloque_idbloque_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bloque_idbloque_seq OWNED BY public.bloque.idbloque;


--
-- Name: bloque_idbloque_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bloque ALTER COLUMN idbloque ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bloque_idbloque_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrera; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carrera (
    idcarrera integer NOT NULL,
    nombrecarrera character varying(20) NOT NULL,
    descripcion character varying(100) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.carrera OWNER TO postgres;

--
-- Name: carrera_idcarrera_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.carrera_idcarrera_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.carrera_idcarrera_seq OWNER TO postgres;

--
-- Name: carrera_idcarrera_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.carrera_idcarrera_seq OWNED BY public.carrera.idcarrera;


--
-- Name: carrera_idcarrera_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carrera ALTER COLUMN idcarrera ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrera_idcarrera_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrera_modulo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carrera_modulo (
    idcarremo integer NOT NULL,
    idmatemo integer NOT NULL,
    idcarrera integer NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.carrera_modulo OWNER TO postgres;

--
-- Name: carrera_modulo_idcarremo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.carrera_modulo_idcarremo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.carrera_modulo_idcarremo_seq OWNER TO postgres;

--
-- Name: carrera_modulo_idcarremo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.carrera_modulo_idcarremo_seq OWNED BY public.carrera_modulo.idcarremo;


--
-- Name: carrera_modulo_idcarremo_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carrera_modulo ALTER COLUMN idcarremo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrera_modulo_idcarremo_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curso; Type: TABLE; Schema: public; Owner: postgres mensualidad
--

CREATE TABLE public.curso (
    idcurso integer NOT NULL,
    nomcurso character varying(20) NOT NULL,
    preciocurso integer NOT NULL,
    nivelcur character varying(100) NOT NULL,
    docenasig character varying(30),
    activo boolean
);


ALTER TABLE public.curso OWNER TO postgres;

--
-- Name: curso_idcurso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.curso_idcurso_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.curso_idcurso_seq OWNER TO postgres;

--
-- Name: curso_idcurso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.curso_idcurso_seq OWNED BY public.curso.idcurso;


--
-- Name: curso_idcurso_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.curso ALTER COLUMN idcurso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curso_idcurso_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: curso_modulo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.curso_modulo (
    idcurso_modulo integer NOT NULL,
    curso integer NOT NULL,
    modulo integer,
    horario integer,
    notas integer NOT NULL
);


ALTER TABLE public.curso_modulo OWNER TO postgres;

--
-- Name: curso_modulo_idcurso_modulo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.curso_modulo_idcurso_modulo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.curso_modulo_idcurso_modulo_seq OWNER TO postgres;

--
-- Name: curso_modulo_idcurso_modulo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.curso_modulo_idcurso_modulo_seq OWNED BY public.curso_modulo.idcurso_modulo;


--
-- Name: curso_modulo_idcurso_modulo_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.curso_modulo ALTER COLUMN idcurso_modulo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curso_modulo_idcurso_modulo_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleado (
    ciempleado character varying NOT NULL,
    nombreempleado character varying(100) NOT NULL,
    apellidoempleado character varying(20) NOT NULL,
    fechacontra date NOT NULL,
    telefempleado character varying(200),
    correoempleado character varying(200),
    activo boolean NOT NULL
);


ALTER TABLE public.empleado OWNER TO postgres;

--
-- Name: estudiante; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estudiante (
    ciestu character varying(30) NOT NULL,
    nombreestu character varying(100) NOT NULL,
    apelliestu character varying(20) NOT NULL,
    teleestu character varying(200),
    correoestu character varying(200),
    activo boolean NOT NULL
);


ALTER TABLE public.estudiante OWNER TO postgres;

--
-- Name: horario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.horario (
    idhorario integer NOT NULL,
    bloque integer NOT NULL,
    dia character varying(30) NOT NULL,
    salon character varying(30) NOT NULL
);


ALTER TABLE public.horario OWNER TO postgres;

--
-- Name: horario_idhorario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.horario_idhorario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.horario_idhorario_seq OWNER TO postgres;

--
-- Name: horario_idhorario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.horario_idhorario_seq OWNED BY public.horario.idhorario;


--
-- Name: horario_idhorario_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.horario ALTER COLUMN idhorario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.horario_idhorario_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materia (
    idmateria integer NOT NULL,
    nombremateria character varying(20) NOT NULL,
    docente character varying(30) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.materia OWNER TO postgres;

--
-- Name: materia_idmateria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.materia_idmateria_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.materia_idmateria_seq OWNER TO postgres;

--
-- Name: materia_idmateria_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.materia_idmateria_seq OWNED BY public.materia.idmateria;


--
-- Name: materia_idmateria_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materia ALTER COLUMN idmateria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materia_idmateria_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materias_modulo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materias_modulo (
    idmatemo integer NOT NULL,
    idmateria integer NOT NULL,
    idmodulo integer NOT NULL
);


ALTER TABLE public.materias_modulo OWNER TO postgres;

--
-- Name: materias_modulo_idmatemo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.materias_modulo_idmatemo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.materias_modulo_idmatemo_seq OWNER TO postgres;

--
-- Name: materias_modulo_idmatemo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.materias_modulo_idmatemo_seq OWNED BY public.materias_modulo.idmatemo;


--
-- Name: materias_modulo_idmatemo_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materias_modulo ALTER COLUMN idmatemo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materias_modulo_idmatemo_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensualidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensualidad (
    idmensualidad integer NOT NULL,
    metodopago character varying(20) NOT NULL,
    monedapago character varying(20) NOT NULL,
    monto integer NOT NULL,
    verificacion boolean NOT NULL,
    encargado integer NOT NULL,
    periodo character varying(20) NOT NULL,
    fecha_corte date NOT NULL,
    fecha_creacion timestamp DEFAULT now() NOT NULL,
    estado varchar(20) DEFAULT 'pendiente' NOT NULL,
    CONSTRAINT mensualidad_pkey PRIMARY KEY (idmensualidad),
    CONSTRAINT chk_mensualidad_estado CHECK (estado IN ('pendiente','pagado','vencido','completado'))
);
--
-- Name: mensualidad_estu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensualidad_estu (
    idmensualidad_estu integer NOT NULL,
    estudiante character varying(20) NOT NULL,
    fechapago date,
    factura character varying(100),
    idmensualidad integer NOT NULL,
    monto_pagado numeric(12,2),
    fecha_vencimiento date NOT NULL,
    fecha_pago date,
    estado varchar(20) DEFAULT 'pendiente' NOT NULL,
    periodo varchar(20) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    CONSTRAINT mensualidad_estu_pkey PRIMARY KEY (idmensualidad_estu),
    CONSTRAINT fk_mensualidad_estu_mensualidad FOREIGN KEY (idmensualidad) REFERENCES public.mensualidad(idmensualidad),
    CONSTRAINT fk_mensualidad_estu_estudiante FOREIGN KEY (estudiante) REFERENCES public.estudiante(ciestu),
    CONSTRAINT chk_mensualidad_estu_estado CHECK (estado IN ('pendiente','pagado','vencido','completado'))
);

CREATE SEQUENCE public.mensualidad_estu_idmensualidad_estu_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.mensualidad_estu_idmensualidad_estu_seq OWNER TO postgres;

ALTER TABLE public.mensualidad_estu
    ALTER COLUMN idmensualidad_estu SET DEFAULT nextval('public.mensualidad_estu_idmensualidad_estu_seq');

CREATE UNIQUE INDEX mensualidad_estu_periodo_idx
    ON public.mensualidad_estu (estudiante, periodo);

--
-- Name: mensualidad_estu_idmensualidad_estu_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensualidad_estu ALTER COLUMN idmensualidad_estu ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensualidad_estu_idmensualidad_estu_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mensualidad_idmensualidad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.mensualidad_idmensualidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mensualidad_idmensualidad_seq OWNER TO postgres;

--
-- Name: mensualidad_idmensualidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.mensualidad_idmensualidad_seq OWNED BY public.mensualidad.idmensualidad;


--
-- Name: mensualidad_idmensualidad_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensualidad ALTER COLUMN idmensualidad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensualidad_idmensualidad_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metodopago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metodopago (
    idmetodopago integer NOT NULL,
    metodousado character varying(20) NOT NULL,
    registro character varying(20) NOT NULL
);


ALTER TABLE public.metodopago OWNER TO postgres;

--
-- Name: metodopago_idmetodopago_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.metodopago_idmetodopago_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.metodopago_idmetodopago_seq OWNER TO postgres;

--
-- Name: metodopago_idmetodopago_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.metodopago_idmetodopago_seq OWNED BY public.metodopago.idmetodopago;


--
-- Name: metodopago_idmetodopago_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.metodopago ALTER COLUMN idmetodopago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metodopago_idmetodopago_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modulo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulo (
    idmodulo integer NOT NULL,
    nombremodulo character varying(10) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.modulo OWNER TO postgres;

--
-- Name: modulo_idmodulo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.modulo_idmodulo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.modulo_idmodulo_seq OWNER TO postgres;

--
-- Name: modulo_idmodulo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.modulo_idmodulo_seq OWNED BY public.modulo.idmodulo;


--
-- Name: modulo_idmodulo_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.modulo ALTER COLUMN idmodulo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modulo_idmodulo_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: monedapago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.monedapago (
    idmoneda integer NOT NULL,
    tipomoneda character varying(40) NOT NULL,
    montototal integer NOT NULL,
    registro character varying(100) NOT NULL
);


ALTER TABLE public.monedapago OWNER TO postgres;

--
-- Name: monedapago_idmoneda_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.monedapago_idmoneda_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.monedapago_idmoneda_seq OWNER TO postgres;

--
-- Name: monedapago_idmoneda_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.monedapago_idmoneda_seq OWNED BY public.monedapago.idmoneda;


--
-- Name: monedapago_idmoneda_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.monedapago ALTER COLUMN idmoneda ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.monedapago_idmoneda_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nota; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nota (
    idnota integer NOT NULL,
    oferta integer NOT NULL,
    notas integer NOT NULL,
    fechanota date NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.nota OWNER TO postgres;

--
-- Name: nota_idnota_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.nota_idnota_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nota_idnota_seq OWNER TO postgres;

--
-- Name: nota_idnota_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.nota_idnota_seq OWNED BY public.nota.idnota;


--
-- Name: nota_idnota_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nota ALTER COLUMN idnota ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nota_idnota_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oferta_seccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.oferta_seccion (
    idseccmo integer NOT NULL,
    idcarremo integer NOT NULL,
    idsecc integer NOT NULL,
    estudiante character varying(25),
    horario integer
);


ALTER TABLE public.oferta_seccion OWNER TO postgres;

--
-- Name: oferta_seccion_idseccmo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.oferta_seccion_idseccmo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.oferta_seccion_idseccmo_seq OWNER TO postgres;

--
-- Name: oferta_seccion_idseccmo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.oferta_seccion_idseccmo_seq OWNED BY public.oferta_seccion.idseccmo;


--
-- Name: oferta_seccion_idseccmo_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.oferta_seccion ALTER COLUMN idseccmo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oferta_seccion_idseccmo_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preguntas_seguridad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preguntas_seguridad (
    idpregunta integer NOT NULL,
    preguntas character varying(40) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.preguntas_seguridad OWNER TO postgres;

--
-- Name: preguntas_seguridad_idpregunta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.preguntas_seguridad_idpregunta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.preguntas_seguridad_idpregunta_seq OWNER TO postgres;

--
-- Name: preguntas_seguridad_idpregunta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.preguntas_seguridad_idpregunta_seq OWNED BY public.preguntas_seguridad.idpregunta;


--
-- Name: preguntas_seguridad_idpregunta_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.preguntas_seguridad ALTER COLUMN idpregunta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preguntas_seguridad_idpregunta_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preguntas_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.preguntas_usuario (
    idpreuser integer NOT NULL,
    ciuser character varying(20) NOT NULL,
    idpregunta integer NOT NULL,
    respuesta character varying(20) NOT NULL
);


ALTER TABLE public.preguntas_usuario OWNER TO postgres;

--
-- Name: preguntas_usuario_idpreuser_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.preguntas_usuario_idpreuser_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.preguntas_usuario_idpreuser_seq OWNER TO postgres;

--
-- Name: preguntas_usuario_idpreuser_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.preguntas_usuario_idpreuser_seq OWNED BY public.preguntas_usuario.idpreuser;


--
-- Name: preguntas_usuario_idpreuser_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.preguntas_usuario ALTER COLUMN idpreuser ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.preguntas_usuario_idpreuser_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id integer NOT NULL,
    token character varying(500) NOT NULL,
    usuario_log integer NOT NULL,
    expira timestamp without time zone NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.refresh_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.refresh_token_id_seq OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.refresh_token_id_seq OWNED BY public.refresh_token.id;


--
-- Name: refresh_token_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    idrol integer NOT NULL,
    nombrerol character varying(40) NOT NULL,
    descripcion character varying(300) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_idrol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rol_idrol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rol_idrol_seq OWNER TO postgres;

--
-- Name: rol_idrol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rol_idrol_seq OWNED BY public.rol.idrol;


--
-- Name: rol_idrol_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN idrol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_idrol_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.seccion (
    idsecc integer NOT NULL,
    nomsecc character varying(10) NOT NULL
);


ALTER TABLE public.seccion OWNER TO postgres;

--
-- Name: seccion_idsecc_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seccion_idsecc_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.seccion_idsecc_seq OWNER TO postgres;

--
-- Name: seccion_idsecc_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.seccion_idsecc_seq OWNED BY public.seccion.idsecc;


--
-- Name: seccion_idsecc_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.seccion ALTER COLUMN idsecc ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seccion_idsecc_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    ciuser character varying(20) NOT NULL,
    nombreusuario character varying(20) NOT NULL,
    apellusuario character varying(100) NOT NULL,
    estudiante character varying(30),
    empleado character varying(30),
    teleusuario character varying(200),
    correousuario character varying(200),
    contrase character varying(100) NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_login; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_login (
    ciuser_log integer NOT NULL,
    ciuser character varying(20) NOT NULL,
    idrol integer NOT NULL,
    activo boolean NOT NULL
);


ALTER TABLE public.usuario_login OWNER TO postgres;

--
-- Name: usuario_login_ciuser_log_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_login_ciuser_log_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_login_ciuser_log_seq OWNER TO postgres;

--
-- Name: usuario_login_ciuser_log_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_login_ciuser_log_seq OWNED BY public.usuario_login.ciuser_log;


--
-- Name: usuario_login_ciuser_log_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario_login ALTER COLUMN ciuser_log ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_login_ciuser_log_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: asignacion_docente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asignacion_docente (id_asignacion_docente, empleado_id, materia_id, seccion_id, fecha_asignacion) FROM stdin;
\.


--
-- Data for Name: asistencias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asistencias (idasis, asisestu, fecha, verificar) FROM stdin;
\.


--
-- Data for Name: auditoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auditoria (idseria, usuario_escritor_id, usuario_objeto_id, accion, datos_anteriores, datos_nuevos, fecha) FROM stdin;
\.


--
-- Data for Name: bloque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bloque (idbloque, horainicio, horafin) FROM stdin;
\.


--
-- Data for Name: carrera; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carrera (idcarrera, nombrecarrera, descripcion, activo) FROM stdin;
1	Diseño de Modas	Creamos profesionales en cuanto al diseño de modas	t
\.


--
-- Data for Name: carrera_modulo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carrera_modulo (idcarremo, idmatemo, idcarrera, activo) FROM stdin;
\.


--
-- Data for Name: curso; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.curso (idcurso, nomcurso, preciocurso, nivelcur, docenasig, activo) FROM stdin;
2	Bordado y Tejido	25000	Principiante	V-25678901	t
\.


--
-- Data for Name: curso_modulo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.curso_modulo (idcurso_modulo, curso, modulo, horario, notas) FROM stdin;
\.


--
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empleado (ciempleado, nombreempleado, apellidoempleado, fechacontra, telefempleado, correoempleado, activo) FROM stdin;
V-25678901	Juan	Zerpa	2025-02-24	+58 422-4321233	Therian69@gmail.com	t
\.


--
-- Data for Name: estudiante; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estudiante (ciestu, nombreestu, apelliestu, teleestu, correoestu, activo) FROM stdin;
V-31122642	Erick	Moncada	+58 414-1235411	lordriczer1105@gmail.com	t
\.


--
-- Data for Name: horario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.horario (idhorario, bloque, dia, salon) FROM stdin;
\.


--
-- Data for Name: materia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materia (idmateria, nombremateria, docente, activo) FROM stdin;
\.


--
-- Data for Name: materias_modulo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materias_modulo (idmatemo, idmateria, idmodulo) FROM stdin;
\.


--
-- Data for Name: mensualidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mensualidad (idmensualidad, metodopago, monedapago, monto, verificacion, encargado) FROM stdin;
\.


--
-- Data for Name: mensualidad_estu; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mensualidad_estu (idmensualidad_estu, estudiante, fechapago, factura) FROM stdin;
\.


--
-- Data for Name: metodopago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.metodopago (idmetodopago, metodousado, registro) FROM stdin;
\.


--
-- Data for Name: modulo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.modulo (idmodulo, nombremodulo, activo) FROM stdin;
\.


--
-- Data for Name: monedapago; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.monedapago (idmoneda, tipomoneda, montototal, registro) FROM stdin;
\.


--
-- Data for Name: nota; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nota (idnota, oferta, notas, fechanota, activo) FROM stdin;
\.


--
-- Data for Name: oferta_seccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.oferta_seccion (idseccmo, idcarremo, idsecc, estudiante, horario) FROM stdin;
\.


--
-- Data for Name: preguntas_seguridad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.preguntas_seguridad (idpregunta, preguntas, activo) FROM stdin;
\.


--
-- Data for Name: preguntas_usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.preguntas_usuario (idpreuser, ciuser, idpregunta, respuesta) FROM stdin;
\.


--
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.refresh_token (id, token, usuario_log, expira, activo) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGZWRvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzg4MDE4NjkyLCJ0eXBlIjoicmVmcmVzaCJ9.e6LXO-WPWuTyEetju_nhmI5hdng1GGciCEgK8IpcFUo	1	2026-08-29 11:51:32.169335	t
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGZWRvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzg4MTAzMTg0LCJ0eXBlIjoicmVmcmVzaCJ9.7VEelVVUcCBPQZVz1kI3og5VK2G7FJaNV-Ij-LwkSGk	1	2026-08-30 11:19:44.146226	t
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGZWRvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzg4MTAzNzIzLCJ0eXBlIjoicmVmcmVzaCJ9.iEYc8BTzJfhhs6R84-_yAG4Kbp9q8eri4zEd_Vl2R0U	1	2026-08-30 11:28:43.343464	t
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGZWRvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzg4MTA0MzA3LCJ0eXBlIjoicmVmcmVzaCJ9.i4LkRF7mekUAylfu1WPbIsTS1q_n-HjZljp7KHlh1vo	1	2026-08-30 11:38:27.323756	t
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJGZWRvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzg4MTgzMDA3LCJ0eXBlIjoicmVmcmVzaCJ9.fT_9iOhkzrdzaylRe1XDHzrtHnRy4Pc3ZQG5igWW5AM	1	2026-08-31 09:30:07.653534	t
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (idrol, nombrerol, descripcion, activo) FROM stdin;
1	Director	El director se encarga de supervisar todo sobre la academia, puede ingresar y regular usuarios dentro del sistema	t
2	Sub Director	El sub director sub directea	t
3	Coordinador	El coordinador supervisa docentes, estudiantes y aveces imparte clases	t
4	Docente	El docente imparte clases, sube notas y asistencias de los estudiantes, tambien puede dar varias materias	t
\.


--
-- Data for Name: seccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.seccion (idsecc, nomsecc) FROM stdin;
1	A
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (ciuser, nombreusuario, apellusuario, estudiante, empleado, teleusuario, correousuario, contrase, activo) FROM stdin;
V-1112233	Fedora	Linux	\N	\N	+58 412-4531211	Fedora123@gmail.com	$2y$10$Ej5huhot.HmI/iZyh5F5vOxhWwM6rZb7xI2eFsalk380igkhMX3d2	t
V-30122345	Reinaldo	Medina	\N	\N	+58 412-3456311	Rchavalin@gmail.com	$2b$12$fjUIRIqsBwLawb1Hw6HMWOc6AqqmDxQYYoE7mSFhhQfntp1nJT6Pi	t
V-23322123	Monica	Morales	\N	\N	+58 412-2214311	Monicam02@gmail.com	$2b$12$Uaip84sx8.GbfzNlXkLCm.VWLARLE1aaDycC8RBlcGRy/dGGUR162	f
\.


--
-- Data for Name: usuario_login; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario_login (ciuser_log, ciuser, idrol, activo) FROM stdin;
1	V-1112233	1	t
\.


--
-- Name: asignacion_docente_id_asignacion_docente_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asignacion_docente_id_asignacion_docente_seq', 1, true);


--
-- Name: asignacion_docente_id_asignacion_docente_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asignacion_docente_id_asignacion_docente_seq1', 1, false);


--
-- Name: asistencias_idasis_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asistencias_idasis_seq', 1, true);


--
-- Name: asistencias_idasis_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asistencias_idasis_seq1', 1, false);


--
-- Name: auditoria_idseria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auditoria_idseria_seq', 1, true);


--
-- Name: auditoria_idseria_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auditoria_idseria_seq1', 1, false);


--
-- Name: bloque_idbloque_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bloque_idbloque_seq', 1, true);


--
-- Name: bloque_idbloque_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bloque_idbloque_seq1', 1, false);


--
-- Name: carrera_idcarrera_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrera_idcarrera_seq', 1, true);


--
-- Name: carrera_idcarrera_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrera_idcarrera_seq1', 1, true);


--
-- Name: carrera_modulo_idcarremo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrera_modulo_idcarremo_seq', 1, true);


--
-- Name: carrera_modulo_idcarremo_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrera_modulo_idcarremo_seq1', 1, false);


--
-- Name: curso_idcurso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_idcurso_seq', 1, true);


--
-- Name: curso_idcurso_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_idcurso_seq1', 2, true);


--
-- Name: curso_modulo_idcurso_modulo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_modulo_idcurso_modulo_seq', 1, true);


--
-- Name: curso_modulo_idcurso_modulo_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.curso_modulo_idcurso_modulo_seq1', 1, false);


--
-- Name: horario_idhorario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.horario_idhorario_seq', 1, true);


--
-- Name: horario_idhorario_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.horario_idhorario_seq1', 1, false);


--
-- Name: materia_idmateria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materia_idmateria_seq', 1, true);


--
-- Name: materia_idmateria_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materia_idmateria_seq1', 1, false);


--
-- Name: materias_modulo_idmatemo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materias_modulo_idmatemo_seq', 1, true);


--
-- Name: materias_modulo_idmatemo_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materias_modulo_idmatemo_seq1', 1, false);


--
-- Name: mensualidad_estu_idmensualidad_estu_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensualidad_estu_idmensualidad_estu_seq', 1, true);


--
-- Name: mensualidad_estu_idmensualidad_estu_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensualidad_estu_idmensualidad_estu_seq1', 1, false);


--
-- Name: mensualidad_idmensualidad_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensualidad_idmensualidad_seq', 1, true);


--
-- Name: mensualidad_idmensualidad_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mensualidad_idmensualidad_seq1', 1, false);


--
-- Name: metodopago_idmetodopago_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metodopago_idmetodopago_seq', 1, true);


--
-- Name: metodopago_idmetodopago_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metodopago_idmetodopago_seq1', 1, false);


--
-- Name: modulo_idmodulo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.modulo_idmodulo_seq', 1, true);


--
-- Name: modulo_idmodulo_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.modulo_idmodulo_seq1', 1, false);


--
-- Name: monedapago_idmoneda_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monedapago_idmoneda_seq', 1, true);


--
-- Name: monedapago_idmoneda_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.monedapago_idmoneda_seq1', 1, false);


--
-- Name: nota_idnota_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nota_idnota_seq', 1, true);


--
-- Name: nota_idnota_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nota_idnota_seq1', 1, false);


--
-- Name: oferta_seccion_idseccmo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oferta_seccion_idseccmo_seq', 1, true);


--
-- Name: oferta_seccion_idseccmo_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.oferta_seccion_idseccmo_seq1', 1, false);


--
-- Name: preguntas_seguridad_idpregunta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.preguntas_seguridad_idpregunta_seq', 1, true);


--
-- Name: preguntas_seguridad_idpregunta_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.preguntas_seguridad_idpregunta_seq1', 1, false);


--
-- Name: preguntas_usuario_idpreuser_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.preguntas_usuario_idpreuser_seq', 1, true);


--
-- Name: preguntas_usuario_idpreuser_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.preguntas_usuario_idpreuser_seq1', 1, false);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 1, true);


--
-- Name: refresh_token_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq1', 5, true);


--
-- Name: rol_idrol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_idrol_seq', 1, true);


--
-- Name: rol_idrol_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_idrol_seq1', 4, true);


--
-- Name: seccion_idsecc_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seccion_idsecc_seq', 1, true);


--
-- Name: seccion_idsecc_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seccion_idsecc_seq1', 1, true);


--
-- Name: usuario_login_ciuser_log_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_login_ciuser_log_seq', 1, true);


--
-- Name: usuario_login_ciuser_log_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_login_ciuser_log_seq1', 1, true);


--
-- Name: asignacion_docente asignacion_docente_empleado_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_docente
    ADD CONSTRAINT asignacion_docente_empleado_id_key UNIQUE (empleado_id);


--
-- Name: asignacion_docente asignacion_docente_materia_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_docente
    ADD CONSTRAINT asignacion_docente_materia_id_key UNIQUE (materia_id);


--
-- Name: asignacion_docente asignacion_docente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_docente
    ADD CONSTRAINT asignacion_docente_pkey PRIMARY KEY (id_asignacion_docente);


--
-- Name: asignacion_docente asignacion_docente_seccion_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asignacion_docente
    ADD CONSTRAINT asignacion_docente_seccion_id_key UNIQUE (seccion_id);


--
-- Name: asistencias asistencias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asistencias
    ADD CONSTRAINT asistencias_pkey PRIMARY KEY (idasis);


--
-- Name: auditoria auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (idseria);


--
-- Name: bloque bloque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bloque
    ADD CONSTRAINT bloque_pkey PRIMARY KEY (idbloque);


--
-- Name: carrera_modulo carrera_modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrera_modulo
    ADD CONSTRAINT carrera_modulo_pkey PRIMARY KEY (idcarremo);


--
-- Name: carrera carrera_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrera
    ADD CONSTRAINT carrera_pkey PRIMARY KEY (idcarrera);


--
-- Name: curso_modulo curso_modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso_modulo
    ADD CONSTRAINT curso_modulo_pkey PRIMARY KEY (idcurso_modulo);


--
-- Name: curso curso_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_pkey PRIMARY KEY (idcurso);


--
-- Name: empleado empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT empleado_pkey PRIMARY KEY (ciempleado);


--
-- Name: estudiante estudiante_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estudiante
    ADD CONSTRAINT estudiante_pkey PRIMARY KEY (ciestu);


--
-- Name: horario horario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horario
    ADD CONSTRAINT horario_pkey PRIMARY KEY (idhorario);


--
-- Name: materia materia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materia
    ADD CONSTRAINT materia_pkey PRIMARY KEY (idmateria);


--
-- Name: materias_modulo materias_modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias_modulo
    ADD CONSTRAINT materias_modulo_pkey PRIMARY KEY (idmatemo);


--
-- Name: mensualidad_estu mensualidad_estu_estudiante_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensualidad_estu
    ADD CONSTRAINT mensualidad_estu_estudiante_key UNIQUE (estudiante);


--
-- Name: mensualidad_estu mensualidad_estu_factura_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensualidad_estu
    ADD CONSTRAINT mensualidad_estu_factura_key UNIQUE (factura);


--
-- Name: mensualidad_estu mensualidad_estu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensualidad_estu
    ADD CONSTRAINT mensualidad_estu_pkey PRIMARY KEY (idmensualidad_estu);


--
-- Name: mensualidad mensualidad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensualidad
    ADD CONSTRAINT mensualidad_pkey PRIMARY KEY (idmensualidad);


--
-- Name: metodopago metodopago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metodopago
    ADD CONSTRAINT metodopago_pkey PRIMARY KEY (idmetodopago);


--
-- Name: modulo modulo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulo
    ADD CONSTRAINT modulo_pkey PRIMARY KEY (idmodulo);


--
-- Name: monedapago monedapago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.monedapago
    ADD CONSTRAINT monedapago_pkey PRIMARY KEY (idmoneda);


--
-- Name: nota nota_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nota
    ADD CONSTRAINT nota_pkey PRIMARY KEY (idnota);


--
-- Name: oferta_seccion oferta_seccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_seccion
    ADD CONSTRAINT oferta_seccion_pkey PRIMARY KEY (idseccmo);


--
-- Name: preguntas_seguridad preguntas_seguridad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preguntas_seguridad
    ADD CONSTRAINT preguntas_seguridad_pkey PRIMARY KEY (idpregunta);


--
-- Name: preguntas_usuario preguntas_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preguntas_usuario
    ADD CONSTRAINT preguntas_usuario_pkey PRIMARY KEY (idpreuser);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_key UNIQUE (token);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (idrol);


--
-- Name: seccion seccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.seccion
    ADD CONSTRAINT seccion_pkey PRIMARY KEY (idsecc);


--
-- Name: usuario usuario_empleado_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_empleado_key UNIQUE (empleado);


--
-- Name: usuario usuario_estudiante_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_estudiante_key UNIQUE (estudiante);


--
-- Name: usuario_login usuario_login_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_login
    ADD CONSTRAINT usuario_login_pkey PRIMARY KEY (ciuser_log);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (ciuser);


--
-- Name: asistencias asistencias_asisestu_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asistencias
    ADD CONSTRAINT asistencias_asisestu_fkey FOREIGN KEY (asisestu) REFERENCES public.estudiante(ciestu);


--
-- Name: auditoria auditoria_usuario_escritor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_usuario_escritor_id_fkey FOREIGN KEY (usuario_escritor_id) REFERENCES public.usuario(ciuser);


--
-- Name: auditoria auditoria_usuario_objeto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_usuario_objeto_id_fkey FOREIGN KEY (usuario_objeto_id) REFERENCES public.usuario(ciuser);


--
-- Name: carrera_modulo carrera_modulo_idcarrera_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrera_modulo
    ADD CONSTRAINT carrera_modulo_idcarrera_fkey FOREIGN KEY (idcarrera) REFERENCES public.carrera(idcarrera);


--
-- Name: carrera_modulo carrera_modulo_idmatemo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrera_modulo
    ADD CONSTRAINT carrera_modulo_idmatemo_fkey FOREIGN KEY (idmatemo) REFERENCES public.materias_modulo(idmatemo);


--
-- Name: curso curso_docenasig_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso
    ADD CONSTRAINT curso_docenasig_fkey FOREIGN KEY (docenasig) REFERENCES public.empleado(ciempleado);


--
-- Name: curso_modulo curso_modulo_curso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso_modulo
    ADD CONSTRAINT curso_modulo_curso_fkey FOREIGN KEY (curso) REFERENCES public.curso(idcurso);


--
-- Name: curso_modulo curso_modulo_horario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso_modulo
    ADD CONSTRAINT curso_modulo_horario_fkey FOREIGN KEY (horario) REFERENCES public.horario(idhorario);


--
-- Name: curso_modulo curso_modulo_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso_modulo
    ADD CONSTRAINT curso_modulo_modulo_fkey FOREIGN KEY (modulo) REFERENCES public.modulo(idmodulo);


--
-- Name: curso_modulo curso_modulo_notas_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.curso_modulo
    ADD CONSTRAINT curso_modulo_notas_fkey FOREIGN KEY (notas) REFERENCES public.nota(idnota);


--
-- Name: horario horario_bloque_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.horario
    ADD CONSTRAINT horario_bloque_fkey FOREIGN KEY (bloque) REFERENCES public.bloque(idbloque) ON DELETE SET NULL;


--
-- Name: materia materia_docente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materia
    ADD CONSTRAINT materia_docente_fkey FOREIGN KEY (docente) REFERENCES public.empleado(ciempleado) ON DELETE SET NULL;


--
-- Name: materias_modulo materias_modulo_idmateria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias_modulo
    ADD CONSTRAINT materias_modulo_idmateria_fkey FOREIGN KEY (idmateria) REFERENCES public.materia(idmateria);


--
-- Name: materias_modulo materias_modulo_idmodulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materias_modulo
    ADD CONSTRAINT materias_modulo_idmodulo_fkey FOREIGN KEY (idmodulo) REFERENCES public.modulo(idmodulo);


--
-- Name: mensualidad_estu mensualidad_estu_estudiante_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensualidad_estu
    ADD CONSTRAINT mensualidad_estu_estudiante_fkey FOREIGN KEY (estudiante) REFERENCES public.estudiante(ciestu);


--
-- Name: oferta_seccion oferta_seccion_estudiante_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_seccion
    ADD CONSTRAINT oferta_seccion_estudiante_fkey FOREIGN KEY (estudiante) REFERENCES public.estudiante(ciestu);


--
-- Name: oferta_seccion oferta_seccion_horario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_seccion
    ADD CONSTRAINT oferta_seccion_horario_fkey FOREIGN KEY (horario) REFERENCES public.horario(idhorario);


--
-- Name: oferta_seccion oferta_seccion_idcarremo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_seccion
    ADD CONSTRAINT oferta_seccion_idcarremo_fkey FOREIGN KEY (idcarremo) REFERENCES public.carrera(idcarrera);


--
-- Name: oferta_seccion oferta_seccion_idsecc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.oferta_seccion
    ADD CONSTRAINT oferta_seccion_idsecc_fkey FOREIGN KEY (idsecc) REFERENCES public.seccion(idsecc);


--
-- Name: preguntas_usuario preguntas_usuario_ciuser_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preguntas_usuario
    ADD CONSTRAINT preguntas_usuario_ciuser_fkey FOREIGN KEY (ciuser) REFERENCES public.usuario(ciuser);


--
-- Name: preguntas_usuario preguntas_usuario_idpregunta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.preguntas_usuario
    ADD CONSTRAINT preguntas_usuario_idpregunta_fkey FOREIGN KEY (idpregunta) REFERENCES public.preguntas_seguridad(idpregunta);


--
-- Name: refresh_token refresh_token_usuario_log_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_usuario_log_fkey FOREIGN KEY (usuario_log) REFERENCES public.usuario_login(ciuser_log);


--
-- Name: usuario usuario_empleado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_empleado_fkey FOREIGN KEY (empleado) REFERENCES public.empleado(ciempleado);


--
-- Name: usuario usuario_estudiante_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_estudiante_fkey FOREIGN KEY (estudiante) REFERENCES public.estudiante(ciestu);


--
-- Name: usuario_login usuario_login_ciuser_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_login
    ADD CONSTRAINT usuario_login_ciuser_fkey FOREIGN KEY (ciuser) REFERENCES public.usuario(ciuser) ON DELETE SET NULL;


--
-- Name: usuario_login usuario_login_idrol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_login
    ADD CONSTRAINT usuario_login_idrol_fkey FOREIGN KEY (idrol) REFERENCES public.rol(idrol) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict etgmknI7bMlJYB9rkT2ylQt81aqJtMrhZ6bPJPXGdJAu2LTOIvqg1xoQbxNjAVO
